name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v4

      - name: Bağımlılıkları kur
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: CMake yapılandır
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Derle
        run: cmake --build build